name: Project X
slug: project-x
branch: master

alias: myOwnDirectory
mirror: ~/Users/Desktop/Code/project-x

vcs: git
sequence: ";"

scripts:
  before:
    all:
      - composer self-update
  after:
    clone:
      - composer install
    update:
      - composer update
      - npm update
    all:
      - gulp
  schedule:
    weekly: php artisan self-update
