name: Project X
slug: project-x
branch: master

alias: myOwnDirectory
mirror: ~/Users/Desktop/Code/project-x

vcs: git
sequence: ";"

scripts:
  before:
    clone:
      - composer self-update
  after:
    clone:
      - composer install
    pull:
      - composer update
      - npm update
