name: Project X
slug: project-x
branch: master
sequence: "|"
mirror: ~/Users/Desktop/Code/project-x
scripts:
  after-clone:
    - composer install
  after-update:
    - composer update
    - npm update
    - gulp
  schedule:
    weekly: php artisan self-update
